workdir: /data/c/yangyusheng_optimized/DIT_HAP_pipeline

project_name: test_project

# Preparation configuration
# -----------------------------------------------------
Pombase_release_version: 2025-05-01

# Preprocessing configuration
# -----------------------------------------------------
sample_sheet: config/sample_sheet_LD.tsv

# Adapter sequences and PBL/PBR sequences for adapter trimming and demultiplexing
# -----------------------------------------------------
adapter_sequence: CTGTCTCTTATACACATCT
adapter_sequence_r2: AGATGTGTATAAGAGACAG
PBL_adapter: CATGCGTCAATTTTACGCAGACTATCTTTCTAGGG
PBL_reverseComplement_adapter: CCCTAGAAAGATAGTCTGCGTAAAATTGACGCATG
PBR_adapter: ACGCATGATTATCTTTAACGTACGTCACAATATGATTATCTTTCTAGGG
PBR_reverseComplement_adapter: CCCTAGAAAGATAATCATATTGTGACGTACGTTAAAGATAATCATGCGT
minimum_length: 30

# Pair read filtering configuration
# -----------------------------------------------------
r1_mapq_threshold: 20
r1_ncigar_value: 1
r1_nm_threshold: 3
r1_no_sa: "--r1-require-no-supplementary"
r1_no_xa: "--r1-require-no-secondary"
r2_mapq_threshold: 20
r2_ncigar_value: "--r2-disable-ncigar"
r2_nm_threshold: "--r2-disable-nm"
r2_no_sa: "--r2-require-no-supplementary"
r2_no_xa: "--r2-require-no-secondary"
require_proper_pair: "--require-proper-pair"

# Chunk size for parallel processing
# -----------------------------------------------------
chunk_size: 3000000

# Merge similar time points configuration
# -----------------------------------------------------
similar_timepoints:
  - "0h"
  - "YES0"
merged_timepoint: "YES0"
drop_columns:
  - "0h"

# Hard filtering configuration and DEseq2 configuration
# -----------------------------------------------------
hard_filtering_cutoff: 16
initial_time_point: "YES0"

# Depletion analysis configuration
# -----------------------------------------------------
time_points:
  - 0
  - 2.352
  - 5.588
  - 9.104
  - 12.480
