workdir: /data/c/yangyusheng_optimized/DIT_HAP_pipeline

project_name: test_project

# Preparation configuration
# -----------------------------------------------------
Pombase_release_version: 2025-05-01

# Preprocessing configuration
# -----------------------------------------------------
sample_sheet: config/sample_sheet_LD.tsv

adapter_sequence: CTGTCTCTTATACACATCT
adapter_sequence_r2: AGATGTGTATAAGAGACAG
PBL_adapter: CATGCGTCAATTTTACGCAGACTATCTTTCTAGGG
PBL_reverseComplement_adapter: CCCTAGAAAGATAGTCTGCGTAAAATTGACGCATG
PBR_adapter: ACGCATGATTATCTTTAACGTACGTCACAATATGATTATCTTTCTAGGG
PBR_reverseComplement_adapter: CCCTAGAAAGATAATCATATTGTGACGTACGTTAAAGATAATCATGCGT
minimum_length: 30


# annotating and normalizing configuration
initial_time_point: "YES0"
first_round_hard_filtering_cutoff: 16

start_timepoint: YES1
unused_timepoints:
  - Diploid
