workdir: /data/c/yangyusheng_optimized/DIT_HAP_pipeline

project_name: LD_DIT_HAP_generationPLUS1

# MultiQC configuration
# -----------------------------------------------------
multiqc_config: config/multiqc_config.yml

# Preparation configuration
# -----------------------------------------------------
Pombase_release_version: 2025-08-01

# Preprocessing configuration
# -----------------------------------------------------
sample_sheet: config/sample_sheet_LD.tsv
use_DEseq2_for_biological_replicates: True

# Adapter sequences and PBL/PBR sequences for adapter trimming and demultiplexing
# -----------------------------------------------------
adapter_sequence: CTGTCTCTTATACACATCT
adapter_sequence_r2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
PBL_adapter: CATGCGTCAATTTTACGCAGACTATCTTTCTAGGG
PBL_reverseComplement_adapter: CCCTAGAAAGATAGTCTGCGTAAAATTGACGCATG
PBR_adapter: ACGCATGATTATCTTTAACGTACGTCACAATATGATTATCTTTCTAGGG
PBR_reverseComplement_adapter: CCCTAGAAAGATAATCATATTGTGACGTACGTTAAAGATAATCATGCGT

# Pair read filtering configuration
# -----------------------------------------------------
r1_mapq_threshold: 20
r1_ncigar_value: 1
r1_nm_threshold: 3
r1_no_sa: "--r1-require-no-supplementary"
r1_no_xa: "--r1-require-no-secondary"
# r1_disable_mapq: "--r1-disable-mapq"
# r1_disable_ncigar: "--r1-disable-ncigar"
# r1_disable_nm: "--r1-disable-nm"

r2_mapq_threshold: 20
# r2_ncigar_value: 1
# r2_nm_threshold: 3
r2_no_sa: "--r2-require-no-supplementary"
r2_no_xa: "--r2-require-no-secondary"
# r2_disable_mapq: "--r2-disable-mapq"
r2_disable_ncigar: "--r2-disable-ncigar"
r2_disable_nm: "--r2-disable-nm"

require_proper_pair: "--require-proper-pair"

# Chunk size for parallel processing
# -----------------------------------------------------
chunk_size: 3000000

# Merge similar time points configuration
# -----------------------------------------------------
similar_timepoints:
  - "0h"
  - "YES0"
merged_timepoint: "YES0"
drop_columns:
  - "0h"

# Hard filtering configuration and DEseq2 configuration
# -----------------------------------------------------
hard_filtering_cutoff: 8
initial_time_point: "YES0"

# Depletion analysis configuration
# -----------------------------------------------------
time_points:
  - 0
  - 3.352
  - 6.588
  - 10.104
  - 13.480
